### ISSUE TITLE
Scanner filter fields

### ISSUE THREAD

**Issue by dougdellolio** [Investor-PAL/Investor-PAL#16]
@gdellolio Min can be greater than max and you can enter non-numeric characters

**Comment by gdellolio** [comment]
non-numeric characters are not a problem. the field auto-corrects it to the default value (0 and 500 mil). working on min max now

**Comment by dougdellolio** [comment]
i feel like it should still throw an error. what do you think

**Comment by gdellolio** [comment]
i dont think it needs to, it doesn't break it at all and no error is thrown.
